import { Open_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/context/AuthContext";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={openSans.variable}>
//       <body className="antialiased bg-dotted font-sans">
//         <AuthProvider>
//           <Navbar />
//           <main>{children}</main>
//           <Footer />
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.variable}>
      <body className="antialiased bg-dotted font-sans">
        <AuthProvider>
          <Navbar />
          {/* Add padding-top to push content down below fixed navbar */}
          <main className="pt-16">{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
