import { Open_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.variable}>
      <body className="antialiased bg-dotted font-sans">
        <AuthProvider>
          <Navbar />
         <Toaster
            position="bottom-right"
            toastOptions={{
              className: "",
              duration: 3000,
              style: {
                fontSize: "16px",
                fontWeight: "500",
                border: "1px solid #ccc",
                padding: "16px",
      
              },
            }}/>
      
          <main className="pt-16">{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
